### ISSUE TITLE
Using arrow keys causes page to scroll up and down

### ISSUE THREAD

**Issue by charleshong3** [pioneers/pimulator#14]
Using the up and down arrow keys to control the gamepad causes the web page to scroll up and down. This can probably be disabled somehow.

**Comment by FIREdog5** [comment]
window.addEventListener("keydown", function(e) {
    if([32, 37, 38, 39, 40].indexOf(e.keyCode) > -1) {
        e.preventDefault();
    }
}, false);

**Comment by FIREdog5** [comment]
this might be useful...
